# Generated by Django 3.0.3 on 2020-02-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_delete_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
    ]
