# Generated by Django 3.0.3 on 2020-02-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_item_is_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchased_by',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
