# Generated by Django 3.0.3 on 2020-02-20 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_auto_20200220_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='list',
        ),
        migrations.DeleteModel(
            name='List',
        ),
    ]
